[package]
name = "audio-player"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.*"
clap = { version = "4.5.*", features = ["derive"]}
glib = "0.20.*"
gstreamer = "0.23.*"
smol = "2.0.*"
termion = "4.0.*"
url = "2.5.*"
